python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'adapter_scaler': 0.1, 'adapter_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-3/config.yaml"

python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-4/config.yaml"

python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/dtd/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/3-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/sun397/6-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/1-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/resisc45/2-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/40-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/diabetic_retinopathy/80-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/clevr_count/20-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"

python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/5-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 4}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-weak/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
python train.py --c "config/lora/supervised/kitti/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck': 16}/lr-1e-5/config.yaml"
