
python train.py --c "config/lora/softmatch/dtd/3-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/dtd/3-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/dtd/3-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/dtd/6-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/dtd/6-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/dtd/6-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/lora/softmatch/sun397/3-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/sun397/3-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/sun397/3-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/sun397/6-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/sun397/6-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/sun397/6-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/lora/softmatch/resisc45/1-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/resisc45/1-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/resisc45/1-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/resisc45/2-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/resisc45/2-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/resisc45/2-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/lora/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/lora/softmatch/clevr_count/10-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/clevr_count/10-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/clevr_count/10-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/clevr_count/20-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/clevr_count/20-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/clevr_count/20-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/lora/softmatch/kitti/5-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/kitti/5-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/kitti/5-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/lora/softmatch/kitti/10-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/lora/softmatch/kitti/10-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/lora/softmatch/kitti/10-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/dtd/3-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/dtd/3-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/dtd/3-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/dtd/6-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/dtd/6-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/dtd/6-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/sun397/3-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/sun397/3-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/sun397/3-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/sun397/6-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/sun397/6-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/sun397/6-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/resisc45/1-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/resisc45/1-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/resisc45/1-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/resisc45/2-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/resisc45/2-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/resisc45/2-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/40-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/clevr_count/10-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/clevr_count/10-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/clevr_count/10-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/clevr_count/20-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/clevr_count/20-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/clevr_count/20-shot/clip/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/softmatch/kitti/5-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/kitti/5-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/kitti/5-shot/clip/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/softmatch/kitti/10-shot/clip/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/softmatch/kitti/10-shot/clip/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/softmatch/kitti/10-shot/clip/lr-1e-5/config.yaml"
