algorithm: pet
save_dir: 
  ./saved_models/config/lora/pet-ensembled-across-nets/dtd/3-shot/qwen3vl
save_name: log
resume: true
load_path: 
  ./saved_models/config/lora/pet-ensembled-across-nets/dtd/3-shot/qwen3vl/log/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 30
num_train_iter: 3420
num_log_iter: 28
num_eval_iter: 228
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 85
num_labels: 141
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: qwen_embedding_builder
net_from_name: false
data_dir: ./data
dataset: dtd
train_sampler: RandomSampler
num_classes: 47
num_workers: 4
seed: 0
world_size: 1
rank: 0
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
# PET settings
w_alpha: 0.0
s_alpha: 0.0
kd_w_alpha: 1.0
kd_s_alpha: 1.0
temperature: 1.0
budget: 1.0
pet_sources:
- "config/adaptformer/supervised/dtd/3-shot/qwen3vl/dpr-0.2/train-aug-strong/{'adapter_scaler':
  0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
- "config/lora/supervised/dtd/3-shot/qwen3vl/dpr-0/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-3/config.yaml"
pl_selection: balanced-max
logits_ensemble: voting
bootstrapping: false
pretrained_path: Qwen3-VL-Embedding-2B
peft_config:
  method_name: lora
  lora_bottleneck: 4
vit_config:
  drop_path_rate: 0.0
pet_sources_rows:
- - adaptformer
  - supervised
  - dtd
  - 3-shot
  - qwen3vl
  - "['dpr-0.2', 'train-aug-strong', \"{'adapter_scaler': 0.1, 'adapter_bottleneck':
    4}\", 'lr-1e-3']"
  - 93.25635528564453
  - 0.16206718875901258
  - 0.03152130193305814
  - 0.21438728677013225
  - 0.25916434380164016
  - 28.608198723283675
  - 0.06732091307640076
  - 0.47021275758743286
  - '2026-04-08 02:52:50'
- - lora
  - supervised
  - dtd
  - 3-shot
  - qwen3vl
  - "['dpr-0', 'train-aug-strong', \"{'lora_bottleneck': 16}\", 'lr-1e-3']"
  - 93.48979187011719
  - 0.23806189482805593
  - 0.10031579733025893
  - 0.29073143088843456
  - 0.2956718629735353
  - 29.983327865600586
  - 0.06757201254367828
  - 0.5914893746376038
  - '2026-04-08 02:52:50'
