
python train.py --c "config/lora/fixmatch/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/fixmatch/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/fixmatch/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/fixmatch/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/fixmatch/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/fixmatch/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/fixmatch/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/fixmatch/kitti/10-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/fixmatch/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/fixmatch/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/fixmatch/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/fixmatch/kitti/10-shot/dinov2/lr-1e-5/config.yaml"
