
python train.py --c "config/lora/finessl/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/finessl/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/finessl/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/finessl/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/finessl/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/finessl/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/finessl/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/finessl/kitti/10-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/finessl/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/finessl/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/finessl/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/finessl/kitti/10-shot/dinov2/lr-1e-5/config.yaml"
