
python train.py --c "config/lora/flexmatch/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/flexmatch/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/flexmatch/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/flexmatch/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/lora/flexmatch/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/lora/flexmatch/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/lora/flexmatch/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/lora/flexmatch/kitti/10-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/dtd/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/dtd/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/dtd/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/dtd/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/dtd/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/dtd/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/sun397/3-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/sun397/3-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/sun397/3-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/sun397/6-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/sun397/6-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/sun397/6-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/resisc45/1-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/resisc45/1-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/resisc45/1-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/resisc45/2-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/resisc45/2-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/resisc45/2-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/40-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/diabetic_retinopathy/80-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/clevr_count/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/clevr_count/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/clevr_count/10-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/clevr_count/20-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/clevr_count/20-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/clevr_count/20-shot/dinov2/lr-1e-5/config.yaml"

python train.py --c "config/adaptformer/flexmatch/kitti/5-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/kitti/5-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/kitti/5-shot/dinov2/lr-1e-5/config.yaml"
python train.py --c "config/adaptformer/flexmatch/kitti/10-shot/dinov2/lr-1e-3/config.yaml"
python train.py --c "config/adaptformer/flexmatch/kitti/10-shot/dinov2/lr-1e-4/config.yaml"
python train.py --c "config/adaptformer/flexmatch/kitti/10-shot/dinov2/lr-1e-5/config.yaml"
